### ISSUE TITLE
avxsynth not available on Stretch

### ISSUE THREAD

**Issue by tango25001** [Jonny007-MKD/multicutmkv#4]
Hello I am using your script on a Raspi to automatically download and cut otrkeys.
Unfortunately avxsynth (especially liblog4cpp5) is not available on stretch (Debian) so I can not build avxsynth.
Does anybody know of a script or a workaround?
Thank you

**Comment by Jonny007-MKD** [comment]
Hi,
funnily I recompiled avxsynth a week ago myself and had the same issue. Please install `liblog4cpp5v5`.

**Comment by tango25001** [comment]
I tried that, but with liblog4cpp5v5 Version (1.1.1-3) installed I get a bunch of errors while compiling avxsynth following their process on guthub.
Did this work for you?
Thx

**Comment by Jonny007-MKD** [comment]
Yes, it did work. I think I installed these dependencies:

1. Build tools
2. MPlayer
3. Log4CPP
4. Cairo
5. Pango

Then I had to rerun `autoreconf -i` to make `configure` happy :)

**Comment by tango25001** [comment]
Which OS are you using?
I followed this instruction 
https://github.com/avxsynth/avxsynth/wiki/System-Setup
but unfortunately with installing liblog4cpp5v5 and not having installed liblog4cpp5 it fails on my Raspi with Stretch.

**Comment by Jonny007-MKD** [comment]
I am also using a Debian Stretch (OSMC) and followed the same instructions.

Here is what I installed from `/var/log/apt/history.log`:
```
apt install build-essential
apt install checkinstall yasm autoconf automake libtool
apt install liblog4cpp5-dev liblog4cpp5v5 mplayer libcairo2-dev libpango1.0-dev
# The other stuff for cutting with multicutmkv
apt install install mkvtoolnix ffmsindex x264
```

Then:
```
autoreconf -i
./configure
make
sudo make install
```

If it still doesn't work, please send me the error (or copy everything to pastebin or something :) )
```

**Comment by tango25001** [comment]
Installing, your mentioned packages, autoreconf and configure run through : see https://pastebin.com/e1vRRwSL
"make" gives me some error at the end : see https://pastebin.com/NziTW3a4
and "sudo make install" aswell : see https://pastebin.com/iErKZAwJ

Thank you very much!

**Comment by Jonny007-MKD** [comment]
Have you installed/compiled some ffms2 stuff? (I never managed to do this and after some time found out I don't need it anyway 👍 )
The error occurs when the avxffms2 plugin is compiled. If you don't need it, you can disable it somewhere. You can definitely disable in the `Makefile`:
`#AVXFFMS2_SUBDIRS = plugins/avxffms2` (**#** comment at the beginning)

Then run `make` again.

**Comment by Jonny007-MKD** [comment]
@Jonny007-MKD Did it work?

**Comment by tango25001** [comment]
Hey Johnny007,

sorry I was on holiday the last couple days, so I wasn't able to test :-)

Just tried it out and it works perfectly!

Thank you very much!!!

**Comment by Jonny007-MKD** [comment]
You're welcome :)
