### ISSUE TITLE
Multicutmkv on Buster

### ISSUE THREAD

**Issue by tango25001** [Jonny007-MKD/multicutmkv#6]
Hello Jonny007,

did you get the script running on Buster yet? Or do you know of an alternative?

Thank you very much

**Comment by Jonny007-MKD** [comment]
Hi tango25001,
what's the problem with buster?
I wanted to make a backup of my RasPi before the upgrade and the faulty sd card reader driver of my pc made me destroy the SD card :( so no, I didn't upgrade my Pi, yet.

**Comment by tango25001** [comment]
I had it running on Stretch, but my Raspi3b died, so I bought a Raspi4.
When I build avxsynth I get I get after the make command:

builtinfunctions/src/filters/convolution.cpp:161:38: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
   if(pbyA && pbyR && pbyG && pbyB == false)

https://pastebin.com/drwTBevQ

dont know what to do

**Comment by Jonny007-MKD** [comment]
Mhm, seems like an error from a more strict c++ compiler.
Please try replacing `pbyB == false` with `pbyB == nullptr`.

**Comment by tango25001** [comment]
I found this:
https://github.com/avxsynth/avxsynth/issues/117
I think this did the trick, was not sure were to put "pbyB == "

but now make exits with

https://pastebin.com/CWAemeXP

If I run make with sudo (since it tells me some permission problem) i get this

https://pastebin.com/ZybhzK9P

**Comment by Jonny007-MKD** [comment]
Perhaps you're missing liblog4cpp-dev?

**Comment by tango25001** [comment]
Liblog4cpp5-dev ist installed. Unfortunately AVXSynth seems to be dead and isn't supportet anymore :-(

Well I will by an "old" Raspi3b+ and put Stretch on again :-)

Thank you very much

**Comment by Jonny007-MKD** [comment]
I am going to compile AVXSynth on a Raspbian Buster in a few weeks or months and then come back to you so you can update to Buster again.

Ein 3B+ wird dir aber wahrscheinlich nicht weiter helfen, du müsstest auch einfach auf den 4er ein Stretch-Image flashen können.

**Comment by tango25001** [comment]
I am going to compile AVXSynth on a Raspbian Buster in a few weeks or months and then come back to you so you can update to Buster again. --> that sounds awesome - thank you 
-----
Stretch und ein Pi4 war keine gute Idee :-) bei mir lief dieser nicht rund ...... :-(
auf dem 3b+ sollte das aber laufen

**Comment by Jonny007-MKD** [comment]
Today I built avxsynth. @scx already fixed all compilation errors, so those should be merged after cloning the repository:
-    https://github.com/avxsynth/avxsynth/pull/120
-    https://github.com/avxsynth/avxsynth/pull/121
-    https://github.com/avxsynth/avxsynth/pull/122

And here is what I did for building:

    sudo apt install build-essential git pkg-config yasm autoconf automake libtool  mplayer liblog4cpp5-dev liblog4cpp5v5 libcairo2-dev libpango1.0-dev libffms2-dev libavcodec-dev libavformat-dev libavutil-dev libpostproc-dev libswscale-dev
    autoreconf -i
    export LDFLAGS="-Wl,--copy-dt-needed-entries"
    ./configure
    make -j4
    sudo make install

**Comment by tango25001** [comment]
Hello Johnny007 I tried building, sorry i am not that familiar with such things. 
I installed the dependencies, then I run the following commands:

`git clone https://github.com/avxsynth/avxsynth.git`
`cd avxsynth/`
`git fetch origin pull/120/head:TEST`
`git fetch origin pull/121/head:TEST`
`git fetch origin pull/122/head:TEST`
`git checkout TEST`
`sudo autoreconf -i`
`export LDFLAGS="-Wl,--copy-dt-needed-entries"`
`sudo ./configure`
`sudo make -j4`
`sudo make install`

but avxsynth is not recogniced by multicut ... do you know what I am doing wrong? 
thank you very very much

**Comment by Jonny007-MKD** [comment]
No problem :) Do you see any errors during `make`?
multicutmkv is testing for the existance of the command `avxFrameServer`

**Comment by Jonny007-MKD** [comment]
I think you cannot fetch the 3 pull requests into one single branch. This worked for me:

    git fetch origin pull/120/head:p120
    git fetch origin pull/121/head:p121
    git fetch origin pull/122/head:p122
    git merge p120
    git merge p121
    git merge p122

**Comment by tango25001** [comment]
I think the mistake was to fetch in one single branch. Now it works!
Thank you very much!

**Comment by Jonny007-MKD** [comment]
great :) you're welcome!
